name: 'CI'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    with:
      python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: test
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt
        python -m unittest
    - name: deploy
      run: echo "deployment placeholder"
